export const FETCH_ALL_SEATS_REQUEST = "FETCH_ALL_SEATS_REQUEST";
export const FETCH_ALL_SEATS_SUCCESS = "FETCH_ALL_SEATS_SUCCESS";
export const FETCH_ALL_SEATS_FAILURE = "FETCH_ALL_SEATS_FAILURE";

export const FETCH_SEATS_REQUEST = "FETCH_SEATS_REQUEST";
export const FETCH_SEATS_SUCCESS = "FETCH_SEATS_SUCCESS";
export const FETCH_SEATS_FAILURE = "FETCH_SEATS_FAILURE";

export const BOOK_TICKET_REQUEST = "BOOK_TICKET_REQUEST";
export const BOOK_TICKET_SUCCESS = "BOOK_TICKET_SUCCESS";
export const BOOK_TICKET_FAILURE = "BOOK_TICKET_FAILURE";

export const CANCEL_TICKET_REQUEST = "CANCEL_TICKET_REQUEST";
export const CANCEL_TICKET_SUCCESS = "CANCEL_TICKET_SUCCESS";
export const CANCEL_TICKET_FAILURE = "CANCEL_TICKET_FAILURE";

export const FETCH_USER_BOOKINGS_REQUEST = "FETCH_USER_BOOKINGS_REQUEST";
export const FETCH_USER_BOOKINGS_SUCCESS = "FETCH_USER_BOOKINGS_SUCCESS";
export const FETCH_USER_BOOKINGS_FAILURE = "FETCH_USER_BOOKINGS_FAILURE";

export const FETCH_USER_DETAILS_REQUEST = "FETCH_USER_DETAILS_REQUEST";
export const FETCH_USER_DETAILS_SUCCESS = "FETCH_USER_DETAILS_SUCCESS";
export const FETCH_USER_DETAILS_FAILURE = "FETCH_USER_DETAILS_FAILURE";

export const RESET_SEATS_REQUEST = "RESET_SEATS_REQUEST";
export const RESET_SEATS_SUCCESS = "RESET_SEATS_SUCCESS";
export const RESET_SEATS_FAILURE = "RESET_SEATS_FAILURE";

export const FETCH_ALL_TRAIN_REQUEST = "FETCH_ALL_TRAIN_REQUEST";
export const FETCH_ALL_TRAIN_SUCCESS = "FETCH_ALL_TRAIN_SUCCESS";
export const FETCH_ALL_TRAIN_FAILURE = "FETCH_ALL_TRAIN_FAILURE";

// ---------------------------------------------------------

export const ADD_TRAIN_DATA = "ADD_TRAIN_DATA";
export const ADD_PASSANGER_DETAIL = "ADD_PASSANGER_DETAIL";
export const GET_TICKET_DETAIL = "GET_TICKET_DETAIL";
